import './globals.scss'
import type { Metadata } from 'next'
import { Dangrek } from 'next/font/google'

const dangrek = Dangrek({weight: "400", subsets: ["latin", "khmer"]});
// dangrek.className = __className_30c698
export const metadata: Metadata = {
  title: 'andvygrams',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={"stripe __className_30c698"}>
        {children}
      </body>
    </html>
  )
}
