import './globals.scss'
import type { Metadata } from 'next'
import { Dangrek } from 'next/font/google'

const dangrek = Dangrek({weight: "400", subsets: ["latin", "khmer"]});
// dangrek.className = __className_30c698
export const metadata: Metadata = {
  title: 'andvygrams',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link
        rel="apple-touch-icon"
        href="/apple-icon?<generated>"
        type="image/<generated>"
        sizes="<generated>"
        />
        <meta name="viewport" content="width=device-width, user-scalable=no"></meta>
      </head>
      <body className={"stripe __className_30c698"}>
        {children}
      </body>
    </html>
  )
}
