import './globals.scss'
import type { Metadata } from 'next'
import { Dangrek } from 'next/font/google'

const dangrek = Dangrek({weight: "400", subsets: ["latin", "khmer"]});
// dangrek.className = __className_30c698
export const metadata: Metadata = {
  title: 'andvygrams',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
        <meta name="viewport" content="width=device-width, user-scalable=no"></meta>
      </head>
      <body className={"stripe __className_30c698"}>
        {children}
      </body>
    </html>
  )
}
